import type { Metadata } from "next";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import { ThemeProvider } from "@mui/material/styles";
import themeAdmin from "./theme-admin";
import Dashboard from "./dashboard/components/dashboard/Dashboard";

export const metadata: Metadata = {
  title: process.env.APP_NAME,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={themeAdmin}>
            <Dashboard>{children}</Dashboard>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html >
  );
}
